include: package:very_good_analysis/analysis_options.yaml
# analyzer:
#   exclude:
#     - '**/*.g.dart'
#     - '**/**/*.g.dart'
#     - '**/*.gr.dart'
#     - '**/**/*.gr.dart'
#     - '**/*.freezed.dart'
#     - '**/**/*.freezed.dart'
#     - '**/*.reflectable.dart'
#     - '**/**/*.reflectable.dart'

#   errors:
#     invalid_annotation_target: ignore
#     directives_ordering: ignore

linter:
  rules:
    public_member_api_docs: false
    
